lidar_obstacle_filter_node:
  ros__parameters:
    ground_relative_low_obstacles_enabled: true
    local_ground_enabled: true
    local_ground_plane_enabled: true

lidar_emergency_stop_node:
  ros__parameters:
    ground_relative_low_obstacles_enabled: true
    local_ground_enabled: true
    local_ground_plane_enabled: true
